#:schema node_modules/wrangler/config-schema.json
name = "wrangler"
main = "dist/workers/server.js"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/workers/assets"
