[package]
name = "remove-server-code"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
swc_core = { version = "0.100.*", features = ["ecma_plugin_transform"] }
