# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: NPM_TOKEN
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install
        run: |
          rustup target add wasm32-wasi
          pnpm install
      - name: Build & Test
        run: |
          cargo test
          pnpm build:pkgs
      - name: Publish to NPM
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          for dir in ./packages/* ; do
            if [ -f "$dir/package.json" ]; then
              ( cd "$dir" && npm publish --access public )
            fi
          done
